-- Seed 24 backgrounds hosted in Supabase Storage (banner-assets bucket)
-- 3-4 per industry, self-hosted PNG images at 1536x1024.
-- Safe to run multiple times — skips rows where name already exists.

INSERT INTO public.banner_backgrounds (name, industry, storage_url, preview_url, is_active, sort_order)
VALUES
  -- Automotive (3)
  ('Automotive 1', 'automotive',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/automotive/automotive-1-1775298019881.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/automotive-1-1775298019881-preview.png',
   true, 1),
  ('Automotive 2', 'automotive',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/automotive/automotive-2-1775298023805.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/automotive-2-1775298023805-preview.png',
   true, 2),
  ('Automotive 3', 'automotive',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/automotive/automotive-3-1775298027347.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/automotive-3-1775298027347-preview.png',
   true, 3),

  -- Construction (4, includes infrastructure)
  ('Construction 1', 'construction',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/construction/construction-1775298036875.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/construction-1775298036875-preview.png',
   true, 1),
  ('Construction 2', 'construction',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/construction/construction-2-1775298030473.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/construction-2-1775298030473-preview.png',
   true, 2),
  ('Construction 3', 'construction',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/construction/construction-3-1775298033505.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/construction-3-1775298033505-preview.png',
   true, 3),
  ('Infrastructure 1', 'construction',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/construction/infrustructure-1-1775298070442.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/infrustructure-1-1775298070442-preview.png',
   true, 4),

  -- Electrical (4)
  ('Electrical 1', 'electrical',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/electrical/electric-1-1775298039983.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/electric-1-1775298039983-preview.png',
   true, 1),
  ('Electrical 2', 'electrical',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/electrical/electric-2-1775298043904.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/electric-2-1775298043904-preview.png',
   true, 2),
  ('Electrical 3', 'electrical',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/electrical/electric-3-1775298047121.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/electric-3-1775298047121-preview.png',
   true, 3),
  ('Electrical 4', 'electrical',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/electrical/electric-4-1775298049949.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/electric-4-1775298049949-preview.png',
   true, 4),

  -- General (3)
  ('General 1', 'general',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/general/general-1-1775298052711.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/general-1-1775298052711-preview.png',
   true, 1),
  ('General 2', 'general',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/general/general-2-1775298056532.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/general-2-1775298056532-preview.png',
   true, 2),
  ('General 3', 'general',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/general/general-3-1775298059101.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/general-3-1775298059101-preview.png',
   true, 3),

  -- Healthcare (3)
  ('Healthcare 1', 'healthcare',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/healthcare/healthcare-1-1775298062401.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/healthcare-1-1775298062401-preview.png',
   true, 1),
  ('Healthcare 2', 'healthcare',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/healthcare/healthcare-2-1775298065503.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/healthcare-2-1775298065503-preview.png',
   true, 2),
  ('Healthcare 3', 'healthcare',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/healthcare/healthcare-3-1775298068131.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/healthcare-3-1775298068131-preview.png',
   true, 3),

  -- Manufacturing (4)
  ('Manufacturing 1', 'manufacturing',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/manufacturing/manufacturing-1-1775298073211.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/manufacturing-1-1775298073211-preview.png',
   true, 1),
  ('Manufacturing 2', 'manufacturing',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/manufacturing/manufacturing-2-1775298076982.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/manufacturing-2-1775298076982-preview.png',
   true, 2),
  ('Manufacturing 3', 'manufacturing',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/manufacturing/manufacturing-3-1775298079992.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/manufacturing-3-1775298079992-preview.png',
   true, 3),
  ('Manufacturing 4', 'manufacturing',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/manufacturing/manufacturing-4-1775298084404.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/manufacturing-4-1775298084404-preview.png',
   true, 4),

  -- Technology (3)
  ('Technology 1', 'technology',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/technology/technology-1-1775298087273.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/technology-1-1775298087273-preview.png',
   true, 1),
  ('Technology 2', 'technology',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/technology/technology-2-1775298090312.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/technology-2-1775298090312-preview.png',
   true, 2),
  ('Technology 3', 'technology',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/backgrounds/technology/technology-3-1775298092594.png',
   'https://xtgwntfwaijeaxkrmmor.supabase.co/storage/v1/object/public/banner-assets/previews/technology-3-1775298092594-preview.png',
   true, 3)
ON CONFLICT DO NOTHING;
