import Link from 'next/link';

export const metadata = {
    title: 'Disclaimer | Imagine Voxa',
    description: 'Legal disclaimer for the Imagine Voxa platform.',
};

export default function DisclaimerPage() {
    const lastUpdated = 'March 30, 2026';

    return (
        <div className="min-h-screen bg-white">
            <div className="max-w-3xl mx-auto px-6 py-16">
                <Link href="/" className="text-violet-600 hover:underline text-sm mb-8 inline-block">
                    ← Back to Imagine Voxa
                </Link>

                <h1 className="text-3xl font-bold text-gray-900 mb-2">Disclaimer</h1>
                <p className="text-sm text-gray-500 mb-10">Last updated: {lastUpdated}</p>

                <div className="prose prose-gray max-w-none space-y-6 text-[15px] leading-relaxed text-gray-700">
                    <section>
                        <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">1. General Disclaimer</h2>
                        <p>
                            The information and content generated by Imagine Voxa is provided on an &quot;as is&quot; and &quot;as available&quot; basis. While we strive to deliver high-quality AI-powered content, we make no warranties or representations of any kind, express or implied, about the completeness, accuracy, reliability, or suitability of the generated content.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">2. AI-Generated Content</h2>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Content generated by our AI tools is based on machine learning models and may not always be accurate, complete, or appropriate for your specific use case.</li>
                            <li>You are solely responsible for reviewing, editing, and approving all AI-generated content before publishing to any platform.</li>
                            <li>Imagine Voxa does not guarantee that generated content will achieve specific business outcomes, engagement metrics, or growth targets.</li>
                            <li>AI-generated images are created using OpenAI&apos;s image generation models and are subject to OpenAI&apos;s usage policies.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">3. Third-Party Platforms</h2>
                        <p>
                            Imagine Voxa integrates with LinkedIn, Facebook, and Instagram for content publishing. We are not responsible for:
                        </p>
                        <ul className="list-disc pl-6 space-y-2 mt-2">
                            <li>Content moderation decisions made by third-party platforms.</li>
                            <li>Changes to third-party APIs that may affect publishing functionality.</li>
                            <li>Account restrictions or bans imposed by third-party platforms as a result of published content.</li>
                            <li>Data handling practices of LinkedIn, Meta, or any other connected platform.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">4. Professional Advice</h2>
                        <p>
                            Content generated by Imagine Voxa does not constitute professional, legal, financial, medical, or any other form of expert advice. If you require professional guidance, consult a qualified professional in the relevant field.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">5. Limitation of Liability</h2>
                        <p>
                            To the fullest extent permitted by law, Imagine Voxa and its operators shall not be held liable for any direct, indirect, incidental, consequential, or special damages arising from:
                        </p>
                        <ul className="list-disc pl-6 space-y-2 mt-2">
                            <li>The use or inability to use the platform.</li>
                            <li>Any content generated, published, or distributed through the platform.</li>
                            <li>Loss of data, revenue, or business opportunities.</li>
                            <li>Service interruptions, bugs, or technical issues.</li>
                            <li>Unauthorized access to your account (if not caused by our negligence).</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">6. Intellectual Property</h2>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>You retain ownership of all brand assets and original content you upload to the platform.</li>
                            <li>AI-generated text and images created through Imagine Voxa are yours to use commercially.</li>
                            <li>The platform itself, including its design, code, and proprietary AI workflows, remains the intellectual property of Imagine Voxa.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">7. External Links</h2>
                        <p>
                            The platform may contain links to external websites or services. We do not control and are not responsible for the content, privacy policies, or practices of any third-party websites.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">8. Changes to This Disclaimer</h2>
                        <p>
                            We reserve the right to modify this disclaimer at any time. Changes will be posted on this page with an updated date. Continued use of the platform after modifications constitutes acceptance of the updated disclaimer.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-3">9. Contact Us</h2>
                        <p>
                            If you have questions about this disclaimer, contact us at{' '}
                            <a href="mailto:arvinrajani71@gmail.com" className="text-violet-600 hover:underline">
                                arvinrajani71@gmail.com
                            </a>.
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
}
